### ISSUE TITLE
Bug on help page?

### ISSUE THREAD

**Issue by harrieklomp** [geokrety/geokrety-website#120]
There is a Google reader field on the help page https://geokrety.org/help.php that somehow not belong there?
Also this is a discontinue part of Google when scrolling down in that field.
![selectie_187](https://user-images.githubusercontent.com/1060518/41977062-c36b60ac-7a1e-11e8-93c1-2af48c095460.png)

**Comment by kumy** [comment]
I'm wondering if we have a sound file available and if another equivalent service exists, else we may have to remove it.

**Comment by kumy** [comment]
This is fixed in new theme: https://new-theme.staging.geokrety.org/help.php#about
Even if it's not yet released, let's close this issue to clean the backlog :)

BTW, this was the first time I heard this "lost mp3 link", are they @filipsPL's family voices? As in French we don't pronounce it like this at all, it give me the idea to record this word in many languages, it could be fun!
