### ISSUE TITLE
Login page is not mobile friendly

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#202]
`search.google.com` has been set for geokrety webstie.

One report view is `Mobile usability`. This tool report the following issue for `login.php` page :

- [ ] Viewport not set
- [ ] Text too small to read
- [ ] Content wider than screen
- [ ] Clickable elements too close together

 (fr) [Google help](https://support.google.com/webmasters/answer/6352293)

**Comment by kumy** [comment]
Link to #4

**Comment by kumy** [comment]
Fixed in new theme 
![Screenshot from 2019-05-21 23-49-00](https://user-images.githubusercontent.com/176794/58133853-57316580-7c25-11e9-8e31-c76fae70f237.png)
![Screenshot_20190522-000619_Firefox_Klar](https://user-images.githubusercontent.com/176794/58133894-7e883280-7c25-11e9-9f40-9cf5a9d8fa36.png)
