### ISSUE TITLE
Update dev environment from Docker Toolbox to Docker for Windows

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#379]
Currently quickstart guide suggests to use Docker Toolbox, however it seems like legacy solution, current recommended way is to use Docker for Windows, see https://docs.docker.com/toolbox/toolbox_install_windows/

If there is no specific reason to use old stuff, it makes sense to update it for a current up-to-date tools

**Comment by kumy** [comment]
I have absolutely no idea of what happens in windows world, maybe @boly38?

**Comment by boly38** [comment]
Hey, You are absolutely right 
Btw docker for Windows rely on Hyper-V with windows 10 as requirement.
At work I'm on windows seven so I will continue to use deprecated docker toolbox.

If you work on it  that's cool because I won't soon.. and keeping the legacy docker toolbox compatibility should maybe not be a problem.

**Comment by kumy** [comment]
GKv2 is based on docker compose for local development (and CI), there is also an Ansible role which deploys on docker swarm (this is what is used on production server)
