### ISSUE TITLE
Improve adoption flow

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#388]
I really tried to look around the pages to find out what do I do if I'd like to give away my GK for "adoption". However I was not able to find anything related to this on the website.

From the code it seems that GKs are available for adoption only if `$userid == 0`, which sounds for me like very-very exceptional case, it shouldn't happen normally.

Probably one would expect some button at own GK page "Suggest for adoption" which can generate "adoption code".

------------

Or, of course, second option is just get rid of all adoption-related logic, if it's not really used :)

**Comment by kumy** [comment]
I'm pretty sure there was already an issue for that, but can't find it.

Adoption is more than `userid=0`, it also need adoption code to be generated. At the moment there not page even in the admin panel to create such. It was only implemented in the "GK batch creation" process.

I agree users should be able to offer their GK for adoption themselves. User must be warned enough about what this process does and the implications.

**Comment by kumy** [comment]
Fixed in `new-theme`.

![2019-08-31_21-16](https://user-images.githubusercontent.com/176794/64068203-edb5ef80-cc34-11e9-9e91-1a62d97bdc3a.png)
![2019-08-31_21-17](https://user-images.githubusercontent.com/176794/64068204-ee4e8600-cc34-11e9-84d1-37db96058598.png)
![2019-08-31_21-18](https://user-images.githubusercontent.com/176794/64068205-edb5ef80-cc34-11e9-9242-6e33388a72dd.png)
