### ISSUE TITLE
[New UI] HTML symbols are escaped on GeoKret page

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#399]
- Check any GK page with HTML in description
- Make sure HTML tags are displayed as text 

https://new-theme.staging.geokrety.org/konkret.php?id=68628#log56858

**Comment by okainov** [comment]
Same in logs texts

**Comment by kumy** [comment]
Link to https://github.com/geokrety/geokrety-website/issues/370

I would to have our database not containing escaped strings, so we need to transform existing database entries "one day". We should take care to not break legacy website, as both sites will live together for some time. There is some workaround on new theme to escape string when read from database. On far end, I would like our database to not contains html at all but pseudo language (ie BBCode) this will greatly help to prevent XSS. I know we use HTML purify but I'm quite paranoiac.

**Comment by okainov** [comment]
Same in caches names (see #422). Not sure if separated issue is needed...

![image](https://user-images.githubusercontent.com/918446/60206431-cb2de180-9853-11e9-9390-c5c8f7fcb86d.png)

Seems like API is giving incorrect response https://new-theme.staging.geokrety.org/check_wpt_name.php?query=%D0%B0%D0%B1%D1%81%D0%BE%D0%BB%D1%8E

**Comment by kumy** [comment]
Seems a badly encoded value in database imports :/

**Comment by okainov** [comment]
Issues on gc.su API side?

**Comment by kumy** [comment]
![Screenshot from 2019-06-26 20-50-43](https://user-images.githubusercontent.com/176794/60206548-1ba53f00-9854-11e9-8a0d-e3fd004e34d5.png)
It's as is in database

**Comment by kumy** [comment]
problem on gc.su side 

https://geocaching.su/?pn=101&cid=21900
![Screenshot from 2019-06-26 20-51-35](https://user-images.githubusercontent.com/176794/60206583-3d9ec180-9854-11e9-8d1b-4b5209312663.png)

**Comment by okainov** [comment]
Fixed on gc.su side, should be good after next full resync

**Comment by kumy** [comment]
…full gc.su resync ongoing…

**Comment by kumy** [comment]
It should be fine now.

**Comment by kumy** [comment]
I've found that all gc.su waypoint name having character `"` in the title are badly encoded on import. This is caused by some weird text trasnformation in import script https://github.com/geokrety/geokrety-scripts/blob/e8c4920a48b3d31f641c7236e128ae6bfe697e07/waypointy/ru/gpx2sql.php#L24

![Screenshot from 2019-07-21 21-17-23](https://user-images.githubusercontent.com/176794/61595886-f4485480-abfc-11e9-8dda-8e133983533b.png)

We should rework this script as done for OC in https://github.com/geokrety/geokrety-scripts/issues/9
