### ISSUE TITLE
Theme refresh

### ISSUE THREAD

**Issue by kumy** [geokrety/geokrety-website#4]
[Imported from bitbuket#49]

Code now include bootstrap, but current layout has not been adapted to follow bootstrap constraints. Templates need to be adapted to use the right css classes. Theme should be responsible.

Edit:
WIP in branch `feature/new-theme`

Preview this branch: https://new-theme.staging.geokrety.org/

**Comment by kumy** [comment]
For information, I was upset with our current design, not mobile friendly, and poor separation of code and template. I'm actively working on this. Please expect huge PR to come in the next days!

**Comment by kumy** [comment]
First preview https://new-theme.staging.geokrety.org/

**Comment by boly38** [comment]
would love that other geokrety contributors give their feedback too :) 
but as it's always WIP, I'll let you manage communication about that point :)

first: only "WaW" 

I will give you a first feedback about this preview, with pro/con points as a good review is,
but would not cancel att all the fact that the job you've done is really impressive 
and like so much the rupture you've done here :) :+1:


+++
- new theme is a big breaking change from prod version, close to fresh standards, Like it so much ! :)
- UI is clear, each block got his place, 
- UI is mobile-compatible : a MUST HAVE you've done in short amount of time : congrats
- You've review in the same time the "lists" style and the backend source code : congrats !
- saw konkret is reviewed too :) waw x2 :) like the "no avatar" placeholder, Parcours


idea to improve
- like you top-banner image on desktop version but absolutely not fan of the mobile one :p mistake?
- HELP/NEWS> we dont have title as we have for home / or maybe we must adapt menu css => "active" for current section only  ? then remove "Accueil" from home
- remove online users section when nobody logged in or else append "anonymous" count ? easy ?
- konkret > "mission" could be "embedded" under "Parcours" to avoid container margin and gain space ?
- konkret > actions could maybe be "embedded" in the first container?
- konkret > for trip steps, maybe "bi-color" (even/odd) style could be use to show that this is a list (like you do for Home>"Recently registered GeoKrety")
- konkret > add full date + time as relative time "tooltip"
- footer > on row only ? 4 rows is too much.
- footer > maybe we need to think about a "contribute" section (improve github readme file) to describe that developpers are welcome :) and add a link in the footer
- "donate" feature missing ?
- todo same theme review for >  user profile page(mypage.php), my inventory(mypage.php?co=5).., new geokrety (register.php)

idea to improve (wording)
- "Open source item tracking for all caching platforms" : I'm not a super english translator but maybe there is a issue in this sentence? caching=>"geocaching" ? gps related games ?
- first sentence : in first general intro sentence I think we need to find a way to describe GeoKrety out of speaking of concurrent offer (TB,lutin). 
    (If I try) GeoKrety a free online service for tracking object in GPS games like geocaching. You can also track book, coins or human with GeoKrety !
- "35996 GeoKrety hidden **by** 41295 users"

**Comment by kumy** [comment]
Thanks for the review. All your point are really easy to solve thanks to the separation of concern. You may already contribute to the `new-theme` branch if you wish, especially regarding the footer part. I still have some code to review on home page. Lots of working is coming this WE!

**Comment by boly38** [comment]
additionnal pending ideas:
- display somewhere "git version" file content (having 2 differents version : one for docker base image, one for geokrety website src ?)

**Comment by kumy** [comment]
@boly38 when you have time may you check what's wrong with the 2 first unit tests on `new-theme` branch about LDJson? See here https://travis-ci.org/geokrety/geokrety-website/jobs/534157010#L837 Thanks

Regarding other tests about trip, they are currently broken cause of recursion in objects. I'll try to fix soon.

**Comment by boly38** [comment]
hi, I'm not available this weekend, as workaround you could fix ld json version to 0.0.14 (from my memory) like I do on another branch. we could postpone that update.

**Comment by okainov** [comment]
Looks really nice from the first look :)  Animated Octocat is awesome =)

Kret page:
- "Social share" links are missing
- Flags have weird blue background
- Click on image actually opens the image. For today's fancy webpages probably it should be some kind of JS slider\popup where one can scroll thru images and close it, still staying on the kret page
- Map is not working?
- Buttons ("edit comment", "remove comment" and so on) seem too small... 

"My recent logs" page
- Exception when trying to sort by distance

`Fatal error: Uncaught exception 'Exception' with message ' prepare failed: (1052) Column 'droga' in order clause is ambiguous' in /var/www/html/lib/geokrety/repository/TripRepository.class.php:83 Stack trace: #0 /var/www/html/lib/geokrety/repository/TripRepository.class.php(275): Geokrety\Repository\TripRepository->getBySql('SELECT ru.ru...', 'd', Array) #1 /var/www/html/mypage.php(84): Geokrety\Repository\TripRepository->getAllTripByAuthorId(29176, 'droga', 'desc', 25, 1) #2 {main} thrown in /var/www/html/lib/geokrety/repository/TripRepository.class.php on line 83`

- If there are no items in the list, it's nicer to show some placeholder "wow, seems you don't have your own GK. DO you want to create one<link>" instead of list with zero elements

Post log page
- If some fields are empty, but hidden, then clicking "Submit" should expand a group where error was detected. Currently user gets no any message if the group with empty mandatory field is hidden
- "Grab" seems like constant string, probably should be updated depending on user choice

Watched GeoKrety page
- Link "log this geokret" (smile link) goes to logging page, however does not fill the tracking code.

General:
- I think current logo is "modern" enough, you should leave this kret-guy, do not remove it.
![image](https://user-images.githubusercontent.com/918446/58582187-7b0e3000-8251-11e9-8e52-a8245c2fbc5c.png)
- Navbar is not being updated when you change pages, "Home" is selected all the time

**Comment by kumy** [comment]
Thanks for first feedback. Bit keep in mind it s just the first draft. (Splitting code and design, implementing fresh design in the same time... Lot of works, and still lot of work.) The log pag eis under construction, it specially working on feedback to users.

If you wish, feel free to open dedicated issue per problem. But honestly I didn t expected such reviews so early!! :) Thanks for taking time to look at it and shared your thoughts!)

**Comment by kumy** [comment]
@boly38 @okainov I've added checkboxes to your logs, added links to existing issues, and marked done features.

Still need to open dedicated issues for all other points :( To both of you, would you be kind to open the dedicated issues? Thanks

**Comment by kumy** [comment]
New implementation require some database changes:
```
ALTER TABLE `gk-ruchy`
CHANGE `alt` `alt` int(5) NULL DEFAULT '-32768' AFTER `lon`,
CHANGE `country` `country` varchar(3) COLLATE 'utf8mb4_unicode_ci' NULL AFTER `alt`,
CHANGE `droga` `droga` int(10) unsigned NULL AFTER `country`,
CHANGE `waypoint` `waypoint` varchar(10) COLLATE 'utf8mb4_unicode_ci' NULL AFTER `droga`
CHANGE `zdjecia` `zdjecia` tinyint(3) unsigned NULL DEFAULT '0' AFTER `koment`,
CHANGE `komentarze` `komentarze` smallint(5) unsigned NULL DEFAULT '0' AFTER `zdjecia`;
```

**Comment by kumy** [comment]
Most work is done, let's continue in small dedicated issues.
