### ISSUE TITLE
templates directory still required at startup

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#509]
While launching local instance of  `new-theme` with `make startlocal` I've got container `geokrety-website_web_1` wich doesn't stay alive.

We've following logs:

```
$ docker logs geokrety-website_web_1
RecursiveDirectoryIterator::__construct(/var/www/html/templates/): failed to open dir: No such file or directory [/var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_compilealltemplates.php:76]
[vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_compilealltemplates.php:76] RecursiveDirectoryIterator->__construct()
[vendor/smarty/smarty/libs/sysplugins/smarty_internal_method_compilealltemplates.php:41] Smarty_Internal_Method_CompileAllTemplates->compileAll()
[vendor/smarty/smarty/libs/sysplugins/smarty_internal_extension_handler.php:133] Smarty_Internal_Method_CompileAllTemplates->compileAllTemplates()
[vendor/smarty/smarty/libs/sysplugins/smarty_internal_data.php:290] Smarty_Internal_Extension_Handler->_callExternalMethod()
[vendor/bcosca/fatfree-core/base.php:1873] GeoKrety\Controller\Cli\SmartyTemplates->compileAllTemplates()
[vendor/bcosca/fatfree-core/base.php:1673] Base->call()
[index.php:47] Base->run()

```

**Comment by boly38** [comment]
should notice that once directory created, container start well, and home page is showed with succes. We have no file nor directory under `website/templates/`

**Comment by kumy** [comment]
we should get rid of it, it's because the default value of `$template_dir` https://www.smarty.net/docs/en/variable.template.dir.tpl

we may convert those 2 lines https://github.com/geokrety/geokrety-website/blob/e812348647611add2b69e320bb529b92f30a71ff/website/app/GeoKrety/Service/Smarty.php#L31-L32

to `Smarty setTemplateDir(string|array template_dir);` https://www.smarty.net/docs/en/api.set.template.dir.tpl

Something like:
```
$smarty->addTemplateDir(array(
 'main' => GK_SMARTY_TEMPLATES_DIR,
 'emails' => GK_SMARTY_FOUNDATION_TEMPLATES_DIR,
));
```
