### ISSUE TITLE
Show all moves in GK maps

### ISSUE THREAD

**Issue by GGGuerin** [geokrety/geokrety-website#607]
![image](https://user-images.githubusercontent.com/77342426/111461089-115c6000-871d-11eb-89ab-78a415b691bd.png)
One can see just the places where the GK go in the page .... here page 3.
Is it possible to see all the GK moves ?
And the "pin" is quite big. Is it possible to decrease the size of the pin ?

**Comment by kumy** [comment]
Funny, I thought about that yesterday :)

I think I'll add an option [one day] to switch between modes

**Comment by kumy** [comment]
From what I saw, the current code
- will show the first 10000 log entries (this is too much and reach a limit in postgres - 1000 is a working value, but it's very long to render in the current map implementation, so I've set it to 500)
- has a bug, the travel is only shown on first page (should be fixed in v2.23.18)

If we really want to show all points, keep the info bubbles with details and with good performance we'll have to choose another method
![image](https://user-images.githubusercontent.com/176794/196027818-11810338-a020-4f20-9cce-0a48c71ca98b.png)

We're in an intermediate state that works for GK having less than 500 visited places.

**Comment by kumy** [comment]
Recent commit allowed the map to continue render when there a re more than 500 moves
