### ISSUE TITLE
Mailing : near my location 0km

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#634]
![Screenshot_20210403-122639](https://user-images.githubusercontent.com/3100576/113475941-7f708900-9478-11eb-8571-b7e2e518fb10.png)

As Gk user, I receive regular mailing about geokrety activity around me.
NB: I think tha maybe this job were disable since a while or there is a poor activity in my location because I got not a lot of activity for 'near my location' table result.

bug? in the table there is always 0km in the distance column cf picture under

username: BSLLM 🙂

**Comment by kumy** [comment]
> bug? in the table there is always 0km in the distance column cf picture under

I'm not sure this is a bug, looking at the first GK in the table, the distance for it's last position - I'm pretty sure distance is less than 1 km - so it's a rounding artifact. We way think in a future to display meters/foot on distances less than 1km..

https://new-theme.staging.geokrety.org/en/geokrety/GK13FF8
![Screenshot from 2021-04-04 10-41-58](https://user-images.githubusercontent.com/176794/113503478-67f5d680-9532-11eb-96ab-48ebb54f8b75.png)


The related part of code for `moves around my home location` has not been touched on GKv1 since 3 years
https://github.com/geokrety/geokrety-scripts/blame/master/obserwacje2.php#L319-L352

So probably not so much GK activity recently in this area? - personally I very rarely receive much data in this particular mail section.

---

Technical on GKv2: I'm current;y working on daily mail feature on GKv2 #614, I will take attention to this area. However, my first thought was : 
> porting should be easy, in new database schema we have a `materialized view` ("dangerous" view which should never been selected without a filter by `c_user_id` else the request will virtually never end :/) for GK near home (It's already used on user homepage to display the map on the bottom right). So it'll just be a matter of filtering by date ;) Should be very easy!!!

In reality, this materialized view contains the current GK states, not the "historical" GK states which we need in daily mails feature. So I have to still find the best way to obtain the data in an efficient non resource hungry way.

But wait, what do we want to know with this mail part ?
- see which GK were moved in my watched location? Including all dipped moves. ("historical moves around me")
- See which GK are physically present in caches around me (drop moves only) at the time of the send mail? This should permit players to go out hunting for touching/collecting them? ("realistic view of GK around me")

I think the second option is preferable ("hunting") - and BTW finally really easy to implement.

@boly38 @GGGuerin  @okainov What do you think?

**Comment by GGGuerin** [comment]
> 

>     * see which GK were moved in my watched location? Including all dipped moves. ("historical moves around me")
> 
>     * See which GK are physically present in caches around me (drop moves only) at the time of the send mail? This should permit players to go out hunting for touching/collecting them? ("realistic view of GK around me")
> 
> 
> I think the second option is preferable ("hunting") - and BTW finally really easy to implement.
> 
> @boly38 @GGGuerin @okainov What do you think?

As for you, i do not see a lot of moves i my area except the mines ! .... But I am more interested by GK which are physically present in caches around me ...

**Comment by boly38** [comment]
sorry for the delay

In fact I've set the home location between my home and Grenoble to have activities
near Crolles city, that's was I was confused 🐡 but the algo is right (under 1km)! 😅
thanks kumy for your detailled feedback! 👍

I'm not sure about giving the distance in meter because ~1km could be suficent (at least for me)

and about your last question, I think like GGGuerin, second option is fine.

As there is no major issue I'll close this one.
