### ISSUE TITLE
Support batch records (one cache -> many GK)

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#668]
As a user having a lot of GK I would like to have an option to mark many of them "in one shot".

Expected flow:
- Select/type a cache
- Select type of GK record (drop/dip)
- Have a multi-select list of all GK in my inventory with the checkboxes and option "select all"
- Same field as now with comments and date

Current workaround is to use c:geo which has such feature. However it has at least two disadvantages:
- Well, it's mobile app. If one wants to write something long, phone is not the best way
- It sends the log to geocaching website. Several times I was just using this and then going to GC website and removing my log (because it was "fake" one just to log GKs). Works, but not ideal.

**Comment by kumy** [comment]
Hi @okainov 
This looks like what has been implemented in GKv2, you can test the feature at https://new-theme.staging.geokrety.org/en/moves

- This is only available to registered and connected users
- We have set a limit ATM to 10 GK per shot

Waiting for your feedback :)

**Comment by okainov** [comment]
Wow, cool, then I assume it's done :)

It feels like new theme is already for quite some time rather usable than not, what is the plan for production deployment? Yeah, I know there is the "checklist-issue", but it feels usable enough anyway. Would you maybe consider deploying it somehow "in parallel" with the main website (like, `new.geokrety.org`, but so they still use the same database)?

**Comment by kumy** [comment]
I still need some time to continue working on it before it can be released. Too much work at home since last months, I hope October will be better for me.

Unfortunately, it's not possible to have both sites working at the same time on the same database, simply because, the whole database structure has been updated on GKv2. That's why there is an automatic import script running each morning to populate the GKv2 database from GKv1. To be honest, this is something I have tried to accomplish at the rewrite beginning but it cause so much troubles that I've abandoned the idea :(

> Wow, cool, then I assume it's done :)

I then close this issue :) Thanks for testing!
