### ISSUE TITLE
geokrety details - update comment - add big image - load forever

### ISSUE THREAD

**Issue by boly38** [geokrety/geokrety-website#742]
- Screen: https://new-theme.staging.geokrety.org/fr/geokrety/GK10288
- seen in [new-theme review](https://github.com/geokrety/geokrety-website/wiki/new-theme---2022-06---Boly38-review---temp-page---wip)

If I go to [a given GK details](https://new-theme.staging.geokrety.org/fr/geokrety/GK10288/page/1#log3376855)

I see my green comment and just add an image 
- file name : pulp_loose.webp
- the file size : 777Ko 
- raw file to be downloadable at https://file.io/9PjV41rCKFcF (keep this link for @kumy please, after download the file is removed)

Then the UI give me some strange behavior:
- query in background while waiting for image to load ? (still in progress :| )
![image](https://user-images.githubusercontent.com/3100576/175530541-c5bea855-e234-4535-946a-4da48729ecc1.png)

Need to double check:
- load image mechanism
- image max size
- image extension valid ?

----

notice after waiting (without action) on the same page; the request change to 404
![image](https://user-images.githubusercontent.com/3100576/175530933-adcf397b-4861-4f6e-a82d-036fb2eb7542.png)

**Comment by kumy** [comment]
I ve never tested a webp image, that maybe be the root issue.. Thanks for the report

**Comment by kumy** [comment]
This is the error returned by ImageMagick
```
data encoding scheme is not supported `/tmp/MOV3352480_62b6b897a412eHrMENM' @ error/webp.c/ReadWEBPImage/338
```

`webp` images are supported by ImageMagick, but it doesn't support animated webp https://github.com/ImageMagick/ImageMagick/issues/22

And more generally, we'll not support animated pictures in general. What's done in the background:
- image is sent to a temporary buck in Minio
- in minio, a webhook is called on `image-processor-downloader` (call it `IPD`)
- IPD read the file
- IPD auto-rotate the image according to metadata and resize the image
- IPD convert the image to `BMP` (that should nuke evil content :crossed_fingers:)
- IPD upload the `BMP` to another temporary bucket on minio
- in minio, a webhook is called on `image-processor-uploader` (call it `IPU`)
- IPU read the file
- IPU convert it to `png`
- IPU upload 2 new files (normal + thumbnail) to their final location
- in minio, a webhook is called to internal website endpoint to say the image is ready

If an error is found in IPD (image cannot be parsed, etc) it calls a special webhook to delete the image from FS and DB.

Thanks to this bug report I've discovered a regression in the delete webhook since the integration of `nginx` in the stack.
Also user now have better feedback about the upload error.

Thanks @boly38!

**Comment by boly38** [comment]
well done 👏 
new test ok ✅ - thanks Kumy 👍

**Comment by kumy** [comment]
webp images are (partially) supported, see #841
