### ISSUE TITLE
Not full list of caches/GK

### ISSUE THREAD

**Issue by okainov** [geokrety/geokrety-website#824]
When doing synchronization between GC.SU database and Geokrety, it seems some GKs are not listed in the API response.

Example https://geokrety.org/konkret.php?id=92829

From `"https://api.geokrety.org/basex/export/geokrety.xml"` it looks like the last update date is old... `2023-04-12T15:09:03.482+02:00">`

**Comment by kumy** [comment]
[GeoKretyMap was stuck](https://api.geokretymap.org/graphs/). Is it better now?

**Comment by okainov** [comment]
Yeah, it got better, thanks, but the users still reports some of GKs inconsistencies:

https://geokrety.org/konkret.php?id=85097 has `state="0"` ("droped") in API response, while the last entry is "grabbed from", so it should not be seen as "in a cache"

https://geokrety.org/konkret.php?id=92834 has weird `state="5"` ("visiting?) in API response, while the last entry is "dropped to", so it should be in a cache.

https://geokrety.org/konkret.php?id=82994 has `state=0` (correct, "dropped in"), but no waypoint (should be [TR19660](https://geocaching.su/?pn=101&cid=19660))

https://geokrety.org/konkret.php?id=91341 and https://geokrety.org/konkret.php?id=93911 have no `state` at all...

**Comment by kumy** [comment]
@okainov may you also provide the api endpoints used in your tests above :pray:

**Comment by okainov** [comment]
@kumy still the same as in the main description :) https://api.geokrety.org/basex/export/geokrety.xml

**Comment by kumy** [comment]
hum, that's an annoying problem...

- If I force the listed GK to refresh in GKM database then they appear with the correct information. (using the dirty endpoint https://api.geokrety.org/gk/85097/dirty ; https://github.com/GeoKretyMap/gkm/wiki/Api-endpoints)
- GKM was an attempt to provide richer and faster api, initially for c:geo when I implemented the GK support. By that time I wasn't the GeoKrety maintainer yet, so I did that side project with what was available to me, mainly by parsing the webpage and cross the data from other internal sources. Some GK parsing have bug, but none of the provided IDs above were impacted.
- Then later when I become GK maintainer, the GKM content was used to provide the exports xml from first message.
- That reminds me #328 
- I did a full refresh last week I would have expected them to be up to date, I just launched a new full refresh, I hope that will be fine that time. I checked [91341](https://geokrety.org/konkret.php?id=91341) as an example and it is in the queue for refresh.
- The next website version will also use a BaseX backend to provide fast responses and the exports too. That was one of the latest addition, I have to admit that I didn't touched GKv2 since December, and I have to double-check that feature again. (I hope I'll can switch to GKv2 during this summer)

I admit this is not a real answer neither a problem fix, but in the future you could try to force refresh bad data using the dirty endpoint. like https://api.geokrety.org/gk/85097/dirty :(

**Comment by kumy** [comment]
Dig deeper into the XQuery code. It appeared that the "Reprocess ALL" [doc](https://github.com/GeoKretyMap/gkm-api-basex/wiki#reprocess-all) was wrong since the beginning. From what I see, the `/dirty` is the only way to force a full GK refresh in GKM (or publishing a new log on a GK). All the previous force re-import I did over the past years were (finally) all unsuccessful :(

The import is now complete, and BTW thanks to the mini fix above, all the ~1000 GK that were always in error are now gone.

Everything should be up to date now.

Thanks for the report and patience :+1:

**Comment by okainov** [comment]
Cool, thanks, then let me close the issue and hope the errors won't come again :) Thank you for looking into this!
