### ISSUE TITLE
GDPR: option to remove an account

### ISSUE THREAD

**Issue by filipsPL** [geokrety/geokrety-website#86]
To comply with GDPR rules we have to add:
- link to remove account

**Comment by boly38** [comment]
good questions... I just give one idea here, because I'm not legal question expert :) 

>Does the created GK are considered as personal data?

not easy to answer.
maybe could we setup in "term of service" (and add a reminder on "remove" action) that geokret you created will be moved into "ready for adoption" state,  when you remove your account ? so we have to handle this state..
Next geokrety users who gets the GK would be able (if they want) to adopt the GK using tracking code.
 
>Do we remove GK along with an account or set owner as some "removed user" value?
I think remove account and contributions but not GK page: 
- set "removed user" as owner name
- remove contributions of the removed user (description/logs/images)
- set "to adopt" as "GK name"


>If GK are effectively traveling, how founders will understand that a GK was deleted?

Maybe add "geokrety engine generated logs" that will trace for everyone the new state of the geokrety maybe loosed distance, loosed logs count, image count.

but maybe "adoption" described here is too complex.. That will be so hard to maintain/explain a GK without data, and GK could be considered as personal data too. So I'm mitiged. 

---
Another point for the"delete" action:
Maybe think of a given delay (to be set using config params, ex. 2 months) between the "want delete" user action and "effective deletion" from geokrety engine. This give some advantages: prevent errors, and allow user to cancel this delete workflow (with huge consequences). But this require to maintain a dedicated state for related data "disabled" or "pending deletion". Not so easy.

**Comment by filipsPL** [comment]
In my opinion, "remove an account" in case of GeoKrety could be just removal of personal information from the user's record in users table (username, email address, user's profile photo) but keeping the record for consistency of the whole system. In such cases we can use a specific username for deleted accounts (ie, "Account Deleted" or any other fancy username like "Doctor No").
